@host = http://localhost:8080

### =========================
### USER API
### =========================

### Получить всех пользователей
GET {{host}}/api/users

### Получить пользователя по ID
GET {{host}}/api/users/1

### Создать пользователя
POST {{host}}/api/tasks
Content-Type: application/json

{
  "title": "Learn Spring",
  "description": "Finish controllers and services",
  "deadline": "2026-03-30",
  "status": "PENDING",
  "user": {
    "id": 1
  }
}

### Обновить задачу
PUT {{host}}/api/tasks/1
Content-Type: application/json

{
  "title": "Complete homework updated",
  "description": "Finish math, science and Spring practice",
  "deadline": "2026-03-22",
  "status": "DONE",
  "user": {
    "id": 1
  }
}

### Удалить задачу
DELETE {{host}}/api/tasks/2

### Обновить пользователя
PUT {{host}}/api/users/1
Content-Type: application/json

{
  "username": "john_doe_updated",
  "email": "john_updated@example.com",
  "password": "newpassword123",
  "role": "USER"
}

### Удалить пользователя
DELETE {{host}}/api/users/2



### =========================
### TASK API
### =========================

### Получить все задачи
GET {{host}}/api/tasks

### Получить задачу по ID
GET {{host}}/api/tasks/1