@host = http://localhost:8080

##################################################
### USER API
##################################################

### Получить всех пользователей
GET {{host}}/api/users

###

### Получить пользователя по ID
GET {{host}}/api/users/1

###

### Получить несуществующего пользователя
GET {{host}}/api/users/999

###

### Создать пользователя
POST {{host}}/api/users
Content-Type: application/json

{
  "username": "alex",
  "email": "alex@example.com",
  "password": "alex123",
  "role": "USER"
}

###

### Обновить пользователя
PUT {{host}}/api/users/1
Content-Type: application/json

{
  "username": "john_doe_updated",
  "email": "john_updated@example.com",
  "password": "newpassword123",
  "role": "USER"
}

###

### Удалить пользователя по ID
DELETE {{host}}/api/users/2

###

### Удалить несуществующего пользователя
DELETE {{host}}/api/users/999


##################################################
### TASK API
##################################################

### Получить все задачи
GET {{host}}/api/tasks

###

### Получить задачу по ID
GET {{host}}/api/tasks/1

###

### Получить несуществующую задачу
GET {{host}}/api/tasks/999

###

### Создать задачу
POST {{host}}/api/tasks
Content-Type: application/json

{
  "title": "Learn Spring",
  "description": "Finish controllers and services",
  "deadline": "2026-03-30",
  "status": "PENDING",
  "user": {
    "id": 1
  }
}

###

### Обновить задачу
PUT {{host}}/api/tasks/1
Content-Type: application/json

{
  "title": "Complete homework updated",
  "description": "Finish math, science and Spring practice",
  "deadline": "2026-03-22",
  "status": "DONE",
  "user": {
    "id": 1
  }
}

###

### Удалить задачу по ID
DELETE {{host}}/api/tasks/2

###

### Удалить несуществующую задачу
DELETE {{host}}/api/tasks/999

###

### Получить задачи пользователя по userId
GET {{host}}/api/tasks/user/1

###

### Получить задачи по статусу PENDING
GET {{host}}/api/tasks/status/PENDING

###

### Получить задачи по статусу IN_PROGRESS
GET {{host}}/api/tasks/status/IN_PROGRESS

###

### Получить задачи по статусу DONE
GET {{host}}/api/tasks/status/DONE